/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodexPluginsRouteImport } from './routes/codex-plugins'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as UpstreamsRouteImport } from './routes/upstreams'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as CodexPluginsIndexRouteImport } from './routes/codex-plugins/index'
import { Route as CodexPluginsMcpRouteImport } from './routes/codex-plugins/mcp'
import { Route as CodexPluginsSkillsRouteImport } from './routes/codex-plugins/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexPluginsRoute = CodexPluginsRouteImport.update({
  id: '/codex-plugins',
  path: '/codex-plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const UpstreamsRoute = UpstreamsRouteImport.update({
  id: '/upstreams',
  path: '/upstreams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexPluginsIndexRoute = CodexPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodexPluginsRoute,
} as any)
const CodexPluginsMcpRoute = CodexPluginsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => CodexPluginsRoute,
} as any)
const CodexPluginsSkillsRoute = CodexPluginsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => CodexPluginsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codex-plugins': typeof CodexPluginsRouteWithChildren
  '/models': typeof ModelsRoute
  '/upstreams': typeof UpstreamsRoute
  '/usage': typeof UsageRoute
  '/codex-plugins/mcp': typeof CodexPluginsMcpRoute
  '/codex-plugins/skills': typeof CodexPluginsSkillsRoute
  '/codex-plugins/': typeof CodexPluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/upstreams': typeof UpstreamsRoute
  '/usage': typeof UsageRoute
  '/codex-plugins/mcp': typeof CodexPluginsMcpRoute
  '/codex-plugins/skills': typeof CodexPluginsSkillsRoute
  '/codex-plugins': typeof CodexPluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codex-plugins': typeof CodexPluginsRouteWithChildren
  '/models': typeof ModelsRoute
  '/upstreams': typeof UpstreamsRoute
  '/usage': typeof UsageRoute
  '/codex-plugins/mcp': typeof CodexPluginsMcpRoute
  '/codex-plugins/skills': typeof CodexPluginsSkillsRoute
  '/codex-plugins/': typeof CodexPluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codex-plugins'
    | '/models'
    | '/upstreams'
    | '/usage'
    | '/codex-plugins/mcp'
    | '/codex-plugins/skills'
    | '/codex-plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/upstreams'
    | '/usage'
    | '/codex-plugins/mcp'
    | '/codex-plugins/skills'
    | '/codex-plugins'
  id:
    | '__root__'
    | '/'
    | '/codex-plugins'
    | '/models'
    | '/upstreams'
    | '/usage'
    | '/codex-plugins/mcp'
    | '/codex-plugins/skills'
    | '/codex-plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodexPluginsRoute: typeof CodexPluginsRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  UpstreamsRoute: typeof UpstreamsRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex-plugins': {
      id: '/codex-plugins'
      path: '/codex-plugins'
      fullPath: '/codex-plugins'
      preLoaderRoute: typeof CodexPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upstreams': {
      id: '/upstreams'
      path: '/upstreams'
      fullPath: '/upstreams'
      preLoaderRoute: typeof UpstreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex-plugins/': {
      id: '/codex-plugins/'
      path: '/'
      fullPath: '/codex-plugins/'
      preLoaderRoute: typeof CodexPluginsIndexRouteImport
      parentRoute: typeof CodexPluginsRoute
    }
    '/codex-plugins/mcp': {
      id: '/codex-plugins/mcp'
      path: '/mcp'
      fullPath: '/codex-plugins/mcp'
      preLoaderRoute: typeof CodexPluginsMcpRouteImport
      parentRoute: typeof CodexPluginsRoute
    }
    '/codex-plugins/skills': {
      id: '/codex-plugins/skills'
      path: '/skills'
      fullPath: '/codex-plugins/skills'
      preLoaderRoute: typeof CodexPluginsSkillsRouteImport
      parentRoute: typeof CodexPluginsRoute
    }
  }
}

interface CodexPluginsRouteChildren {
  CodexPluginsMcpRoute: typeof CodexPluginsMcpRoute
  CodexPluginsSkillsRoute: typeof CodexPluginsSkillsRoute
  CodexPluginsIndexRoute: typeof CodexPluginsIndexRoute
}

const CodexPluginsRouteChildren: CodexPluginsRouteChildren = {
  CodexPluginsMcpRoute: CodexPluginsMcpRoute,
  CodexPluginsSkillsRoute: CodexPluginsSkillsRoute,
  CodexPluginsIndexRoute: CodexPluginsIndexRoute,
}

const CodexPluginsRouteWithChildren = CodexPluginsRoute._addFileChildren(
  CodexPluginsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodexPluginsRoute: CodexPluginsRouteWithChildren,
  ModelsRoute: ModelsRoute,
  UpstreamsRoute: UpstreamsRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
